# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

dist: trusty

php:
  - 5.6

env:
  global:
    - COMPOSER_ROOT_VERSION=5.0.x-dev
    - SS_BASE_URL="https://localhost/"

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
      env:
        - DB=MYSQL
        - RECIPE_VERSION=1.0.x-dev
        - PHPCS_TEST=1
    - php: 7.0
      env:
        - DB=MYSQL
        - RECIPE_VERSION=1.1.x-dev
    - php: 7.1
      env:
        - DB=MYSQL
        - PHPSTAN_TEST=1
        - RECIPE_VERSION=1.2.x-dev
    - php: 7.2
      env:
        - DB=MYSQL
        - PHPSTAN_TEST=1
        - RECIPE_VERSION=1.2.x-dev

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - if [[ $PHPSTAN_TEST ]]; then composer require --no-update phpstan/phpstan-shim:0.9.2; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --ignore=src/SilbinaryWolf/Components/ComponentTemplateParser.php src/ tests/ -n; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse src/ tests/ -c ".phpstan.neon" -a "tests/bootstrap-phpstan.php" --level 3; fi
  - vendor/bin/phpunit
